// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtbTBT6x1Nco-WYU4CgRJXEpQRjc46uxE',
    appId: '1:226170811222:android:6a473c02e0ea1bec775cf7',
    messagingSenderId: '226170811222',
    projectId: 'free-y-fi',
    storageBucket: 'free-y-fi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX3rFy1LuZ0osbsq0fOphjdg9bKz-dhos',
    appId: '1:226170811222:ios:24a3140b8cdec838775cf7',
    messagingSenderId: '226170811222',
    projectId: 'free-y-fi',
    storageBucket: 'free-y-fi.firebasestorage.app',
    androidClientId: '226170811222-f61sed0oejs0sh9mgfbi84hk3kh660ne.apps.googleusercontent.com',
    iosClientId: '226170811222-39a5g6ge7q45k2ffackv3lbr0i26l8b0.apps.googleusercontent.com',
    iosBundleId: 'org.braincount.braincount',
  );
}
